# Generated by Django 5.1.4 on 2025-04-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_favorite_unique_together_favorite_overview_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'content_id', 'content_type')},
        ),
    ]
